language: node_js

node_js:
  - '8.10'

install:
  - yarn install

script:
  - yarn run lint
  # - yarn run test

# after_success:
#   - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage

deploy:
  provider: npm
  email: accounts@acloud.guru
  api_key:
    secure: BPJzu1ilyf7GVJMitB8FIUo2x/nyOlqrF3cteEBRDGLWAHt+/EICwgnswdrO2Y4pGOMOrq6ZORJ6KfMw4eFPRv/Ox+z+4ZZ/j1dd7l8+1hoXzf4+BTmieqrI8DZsCon6UbOQqg8e6eh6ExIc7KfsZZv0gsLuQwONNTM37JOIEjdhakg3RAWpQ6pi1DVEfolJLh4DeW0fUFnUcYjpVSc6xxJweO8RXTfsfWan2qxc6/Ig05RWnSMFFKxJX9R/FbZ5CO59FY9pqoNFf/b3NJRV+pqK3Fg0G0uBI1Zd9bNaOh8Gt55gfdtNAhdOFhHu1h3huh+LED+sebBzq2rUcP77Kloa0kQVQOpqoWZm49Z13xApSKBvKmge1oeeV8EaFIUWnt1sVrVRtthKMXu54m+mXulMu3SFHGLyZSyoBXKaTEr3n8YvCxl+0P1UbdOtSBGSgp3lUZf2Z0tMeufRPrMAV6zLQq9b9OCxZGmQPAn/lCEki0Zb02BFOTcUwmt/kSZJ5U9X4mjNVD49GF080pNte8NySOAYnxFq9LkJ0GFPSxzZnp5qTMIKIAuqWEO2YRE+b41NTpr7toYoQPrmgWduYoHmz9fdMYPTd38UH96Gu5PPI/iniVoXm6SxMQRf9kEwOEcDcpye7qZshSiy2hk2vyUogth+8/EZ4VGYTHi7JxU=
  on:
    tags: true
    repo: ACloudGuru/oprah
    branch: master
    node: '8.10'
