service: oprah-resources
provider:
  name: aws

resources:
  Resources:
    ServiceKeyAlias:
      Type: AWS::KMS::Alias
      Properties:
        AliasName: "alias/oprah-key-${opt:stage}"
        TargetKeyId:
          Ref: ServiceKey

    ServiceKey:
      Type: AWS::KMS::Key
      Properties:
        Description: "The key used to encrypt and decrypt env vars"
        KeyPolicy:
          Version: "2012-10-17"
          Id: "oprah-key-policy-${opt:stage}"
          Statement:
            - Sid: "Enable IAM User Permissions"
              Effect: Allow
              Principal:
                AWS: arn:aws:iam::${env:AWS_ACCOUNT_ID}:root
              Action:
                - kms:*
              Resource: "*"
            - Sid: "Allow lambda to decrypt"
              Effect: "Allow"
              Principal:
                AWS:
                  -
                    "Fn::GetAtt": [ LambdaExecutionRole, Arn ]
              Action:
                - kms:Decrypt
              Resource: "*"

    LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: "oprah-lambda-role-${opt:stage}"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: "assumeOprahRolePolicy"
              Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        Policies:
          - PolicyName: oprah-lambda-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - ssm:GetParameters
                  Resource:
                    - arn:aws:ssm:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:parameter/${opt:stage}/oprah/*

  Outputs:
    LambdaRole:
      Description: "Lambda Execution Role Arn"
      Value:
        "Fn::GetAtt": [ LambdaExecutionRole, Arn ]
    keyAlias:
      Description: "Encryption key for SSM Parameter store"
      Value:
        Ref: "ServiceKeyAlias"

